{
  "openapi": "3.0.1",
  "info": {
    "title": "pet233-gitmodi",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "pet"
    }
  ],
  "paths": {
    "/pet/{petId}": {
      "get": {
        "summary": "Find pet by ID",
        "deprecated": false,
        "description": "",
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "pet ID",
            "required": true,
            "example": "1",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0,
                      "description": "status code"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "pet details"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "Success example",
                    "value": {
                      "code": 0,
                      "data": {
                        "name": "Hello Kity",
                        "photoUrls": [
                          "http://dummyimage.com/400x400"
                        ],
                        "id": 3,
                        "category": {
                          "id": 71,
                          "name": "Cat"
                        },
                        "tags": [
                          {
                            "id": 22,
                            "name": "Cat"
                          }
                        ],
                        "status": "sold"
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "message"
                  ]
                }
              }
            },
            "headers": {}
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "message": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "code",
                    "message"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "Deletes a pet",
        "deprecated": false,
        "description": "",
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "petId",
            "in": "path",
            "description": "Pet id to delete",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "api_key",
            "in": "header",
            "description": "",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0
                    }
                  },
                  "required": [
                    "code"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "Success example",
                    "value": {
                      "code": 0
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pet": {
      "post": {
        "summary": "Add a new pet to the store",
        "deprecated": false,
        "description": "",
        "tags": [
          "pet"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "description": "Pet Name",
                    "example": "Hello Kitty",
                    "type": "string"
                  },
                  "status": {
                    "description": "Pet Sales Status",
                    "example": "sold",
                    "type": "string"
                  }
                },
                "required": [
                  "name",
                  "status"
                ]
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "minimum": 0,
                      "maximum": 0
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "pet details"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "Success example",
                    "value": {
                      "code": 0,
                      "data": {
                        "name": "Hello Kity",
                        "photoUrls": [
                          "http://dummyimage.com/400x400"
                        ],
                        "id": 3,
                        "category": {
                          "id": 71,
                          "name": "Cat"
                        },
                        "tags": [
                          {
                            "id": 22,
                            "name": "Cat"
                          }
                        ],
                        "status": "sold"
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "Update an existing pet",
        "deprecated": false,
        "description": "",
        "tags": [
          "pet"
        ],
        "parameters": [],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {}
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    },
                    "data": {
                      "$ref": "#/components/schemas/Pet",
                      "description": "pet details"
                    }
                  },
                  "required": [
                    "code",
                    "data"
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "Success example",
                    "value": {
                      "code": 0,
                      "data": {
                        "name": "Hello Kity",
                        "photoUrls": [
                          "http://dummyimage.com/400x400"
                        ],
                        "id": 3,
                        "category": {
                          "id": 71,
                          "name": "Cat"
                        },
                        "tags": [
                          {
                            "id": 22,
                            "name": "Cat"
                          }
                        ],
                        "status": "sold"
                      }
                    }
                  }
                }
              }
            },
            "headers": {}
          },
          "404": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          },
          "405": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/pet/findByStatus": {
      "get": {
        "summary": "Finds Pets by status",
        "deprecated": false,
        "description": "",
        "tags": [
          "pet"
        ],
        "parameters": [
          {
            "name": "status",
            "in": "query",
            "description": "Status values that need to be considered for filter",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Pet",
                    "description": "pet details"
                  }
                },
                "examples": {
                  "1": {
                    "summary": "Success example",
                    "value": {
                      "code": 0,
                      "data": [
                        {
                          "name": "Hello Kity",
                          "photoUrls": [
                            "http://dummyimage.com/400x400"
                          ],
                          "id": 3,
                          "category": {
                            "id": 71,
                            "name": "Cat"
                          },
                          "tags": [
                            {
                              "id": 22,
                              "name": "Cat"
                            }
                          ],
                          "status": "sold"
                        },
                        {
                          "name": "White Dog",
                          "photoUrls": [
                            "http://dummyimage.com/400x400"
                          ],
                          "id": 3,
                          "category": {
                            "id": 71,
                            "name": "Dog"
                          },
                          "tags": [
                            {
                              "id": 22,
                              "name": "Dog"
                            }
                          ],
                          "status": "sold"
                        }
                      ]
                    }
                  }
                }
              }
            },
            "headers": {}
          },
          "400": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "code"
                  ]
                }
              }
            },
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "components": {
    "schemas": {
      "Pet": {
        "required": [
          "name",
          "photoUrls",
          "id",
          "category",
          "tags",
          "status"
        ],
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "Pet ID"
          },
          "category": {
            "$ref": "#/components/schemas/Category",
            "description": "group"
          },
          "name": {
            "type": "string",
            "description": "name",
            "examples": [
              "doggie"
            ]
          },
          "photoUrls": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "description": "image URL"
          },
          "tags": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Tag"
            },
            "description": "tag"
          },
          "status": {
            "type": "string",
            "description": "Pet Sales Status",
            "enum": [
              "available",
              "pending",
              "sold"
            ]
          }
        }
      },
      "Category": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "Category ID"
          },
          "name": {
            "type": "string",
            "description": "Category Name"
          }
        }
      },
      "Tag": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "format": "int64",
            "minimum": 1,
            "description": "Tag ID"
          },
          "name": {
            "type": "string",
            "description": "Tag Name"
          }
        }
      }
    },
    "securitySchemes": {}
  },
  "servers": []
}

